on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
name: Test Angular
jobs:
  build:
    runs-on: ubuntu-latest
    environment: avans-app-2-2
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install -g npm@latest
      - run: npm install -g @angular/cli
      - run: npm install
        working-directory: ./Frontend
      - run: npm run test:prod
        working-directory: ./Frontend
